# File included by gateway.yaml to set up the spring-gateway's routes
# target service URL's are defined in gateway.yaml (e.g. georchestra.gateway.services.<service>.target)

spring:
  cloud:
    gateway:
      routes:
      - id: root
        uri: ${georchestra.gateway.services.header.target}
        predicates:
        - Path=/
        filters:
        - RewritePath=/, /header
      - id: loginredirect
        uri: no://op
        predicates:
        - Path=/header
        - QueryParam=login
        filters:
        - RedirectTo=308, /login
      - id: header
        uri: ${georchestra.gateway.services.header.target}
        predicates:
        - Path=/header,/header/**
      - id: analytics
        uri: ${georchestra.gateway.services.analytics.target}
        predicates:
        - Path=/analytics/**
      - id: atlas
        uri: ${georchestra.gateway.services.atlas.target}
        predicates:
        - Path=/atlas/**
      - id: console
        uri: ${georchestra.gateway.services.console.target}
        predicates:
        - Path=/console/**
      - id: extractorapp
        uri: ${georchestra.gateway.services.extractorapp.target}
        predicates:
        - Path=/extractorapp/**
      - id: geonetwork
        uri: ${georchestra.gateway.services.geonetwork.target}
        predicates:
        - Path=/geonetwork/**
      - id: geoserver
        uri: ${georchestra.gateway.services.geoserver.target}
        predicates:
        - Path=/geoserver/**
      - id: mapfishapp
        uri: ${georchestra.gateway.services.mapfishapp.target}
        predicates:
        - Path=/mapfishapp/**
      - id: geowebcache
        uri: ${georchestra.gateway.services.geowebcache.target}
        predicates:
        - Path=/geowebcache/**
      - id: mapstore
        uri: ${georchestra.gateway.services.mapstore.target}
        predicates:
        - Path=/mapstore/**
      - id: datafeeder
        uri: ${georchestra.gateway.services.datafeeder.target}
        predicates:
        - Path=/datafeeder/**
      - id: import
        uri: ${georchestra.gateway.services.import.target}
        predicates:
        - Path=/import/**

georchestra.gateway.services:
  analytics.target: http://analytics:8080/analytics/
  atlas.target: http://atlas:8080/atlas/
  console.target: http://console:8080/console/
  datafeeder.target: http://datafeeder:8080/datafeeder
  extractorapp.target: http://extractorapp:8080/extractorapp/
  geonetwork.target: http://geonetwork:8080/geonetwork/
  geoserver.target: http://geoserver:8080/geoserver/
  geowebcache.target: http://geowebcache:8080/geowebcache/
  header.target: http://header:8080/header/
  import.target: http://import:80/
  mapfishapp.target: http://mapfishapp:8080/mapfishapp/
  mapstore.target: http://mapstore:8080/mapstore/
