server:
  port: 8080
#  address: localhost
#  forward-headers-strategy: NATIVE
#  servlet:
#    context-path: /ogcapi
  instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}}:${server.port}
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  application.name: ogc-records-service
  main.banner-mode: off
  cloud:
    loadbalancer.ribbon.enabled: false # ribbon is in maintenance mode and should be replaced by spring-cloud-loadbalancer
    config:
      fail-fast: true
      retry:
        max-attempts: 20
      discovery:
        enabled: true
        service-id: config-service

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${server.instance-id}
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: ${eureka.server.url:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

---
# Use this profile when running on a GN4 database on localhost and Elasticsearch index.
# Turn off security, config & discover.
spring:
  profiles: standalone
  rabbitmq.host: localhost
  datasource:
    driver-class-name: org.postgresql.Driver
    # Provided by environment variables instead
    #url: jdbc:postgresql://haproxy.postgres-12-geo2france:5432/georchestra
    #username: geonetwork
    #password: georchestra
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.generate-ddl: false
    jpa.hibernate.ddl-auto: none
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
management:
  health.ldap.enabled: false
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetch-registry: false
gn:
  baseurl: https://${FQDN}/ogc-api-records
  language:
    default: fre
  legacy.url: https://${FQDN}/geonetwork
  linkToLegacyGN4: true
  index:
    url: http://${ES_HOST}-svc:9200
    records: gn-records
    username:
    password:
  search:

    formats:
      - name: html
        mimeType: text/html
        responseProcessor: JsonUserAndSelectionAwareResponseProcessorImpl
        operations:
          - root
          - collections
          - collection
          - items
          - item
      - name: xml
        mimeType: application/xml
        responseProcessor: XmlResponseProcessorImpl
        operations:
          - root
          - collections
          - collection
          - items
          - item
      - name: json
        mimeType: application/json
        responseProcessor: JsonUserAndSelectionAwareResponseProcessorImpl
        operations:
          - root
          - collections
          - collection
          - items
          - item
      - name : gn
        mimeType : application/gn+xml
        responseProcessor: XsltResponseProcessorImpl
      - name: opensearch
        mimeType: application/opensearchdescription+xml
        operations:
          - collection
      - name : schema.org
        mimeType : application/ld+json
        responseProcessor: JsonLdResponseProcessorImpl
        operations:
          - items
          - item
      - name: dcat
        mimeType: application/rdf+xml
        responseProcessor: JsonUserAndSelectionAwareResponseProcessorImpl
        operations:
          - item
      - name : dcat_turtle
        mimeType : text/turtle
        responseProcessor: JsonUserAndSelectionAwareResponseProcessorImpl
        operations :
          - item
      - name : rss
        mimeType : application/rss+xml
        responseProcessor: RssResponseProcessorImpl
        operations:
          - items
    defaultMimeType: text/html

logging:
  level:
    # geonetwork roots
    org.fao.geonet: INFO
    org.fao.geonet.ogcapi: INFO
    org.fao.geonet.searching: INFO
springfox:
  documentation:
    swaggerUi:
      baseUrl: /openapi
    openApi:
      v3:
        path: /openapi/v3/api-docs
    swagger:
      v2 :
        path: /openapi/v2/api-docs
